### ISSUE TITLE
Add `sequencer getblock` command

### ISSUE THREAD

**Issue by steezeburger** [astriaorg/astria-cli-go#97]
> We should probably have a get_block or GetBlock or w/e casing we’re using in go land.
The reason I ask is because I’m trying to understand how various stuff works, we emit Deposit events when a BridgeLock is sent to a bridge account, would be cool if I had the ability to:
> * create a bridge account
> * transfer to it
> * look at block
> * bridge lock to it
> * look at block
> 
> And observe that there is a Deposit event

**Comment by jbowen93** [comment]
Where are the `Deposit` events stored in the `SequencerBlock`?

> They are there they are in the transactions  of the `rollup_transactions` those bytes are protobuf encoded `RollupData`. Which has a oneof of either `Deposit` or bytes of `sequenced_data`. They are bytes that need further decoded for merkle tree verification purposes.


[`GetSequencerBlock`](https://buf.build/astria/sequencerblock-apis/docs/main:astria.sequencerblock.v1alpha1#astria.sequencerblock.v1alpha1.SequencerService.GetSequencerBlock)

[`Deposit`](https://buf.build/astria/sequencerblock-apis/docs/main:astria.sequencerblock.v1alpha1#astria.sequencerblock.v1alpha1.Deposit)

[`astria-geth GetDeposit()`](https://github.com/astriaorg/astria-geth/blob/e21153daa19bf8ada70df0cd79f60abdc5c21ac1/grpc/execution/server.go#L256-L257)

```
SequencerBlock {
  ...
  RollupTransactions: []{
    {
      RollupId: 1
      Transactions: []{
        {<rollup serialized data>},
        {<sequencer serialized deposit},
      }
    }
  }
}
```

**Comment by jbowen93** [comment]
The Sequencer API gives you a [SequencerBlock](https://buf.build/astria/sequencerblock-apis/docs/66d6f20a25a24469af6aa676e833cfa8:astria.sequencerblock.v1alpha1#astria.sequencerblock.v1alpha1.SequencerBlock) which contains [RollupTransactions](https://buf.build/astria/sequencerblock-apis/docs/66d6f20a25a24469af6aa676e833cfa8:astria.sequencerblock.v1alpha1#astria.sequencerblock.v1alpha1.RollupTransactions) which has a repeated transactions field which is implicitly the serialized bytes for [RollupData](https://buf.build/astria/sequencerblock-apis/docs/66d6f20a25a24469af6aa676e833cfa8:astria.sequencerblock.v1alpha1#astria.sequencerblock.v1alpha1.RollupData).

Using the Sequencer API to retrieve a block will not give you the `RollupData` object, but this is protobuf encoded, so it should be able to do something like the pseudo code:
```
for (per_rollup_txs in rollup_transactions) {
  for (txs in per_rollup_txs) {
    for (tx in txs) {
      RollupData data = tx.deserialize()
    }
  }
}
```

**Comment by sambukowski** [comment]
closed by https://github.com/astriaorg/astria-cli-go/pull/104
